---
  - { include: file_downloader.yaml, url: "{{nagios_plugins_url}}", dest: "{{home_directory}}" }

  - name: extract nagios plugins tarball
    unarchive: src={{home_directory}}/{{plugins_file_version}}.tar.gz
               dest={{home_directory}}
               copy=no
    register: unarchive
