---

  - { include: file_downloader.yaml, url: "{{nagios_plugins_url}}", dest: "{{home_directory}}" }

  - { include: unarchiver.yaml, directory: "{{home_directory}}", file: "{{plugins_file_version}}", dest: "{{home_directory}}" }
