file_version: "nagios-4.1.0rc1.tar.gz"
nagios_core_url: "http://sourceforge.net/projects/nagios/files/nagios-4.x/nagios-4.1.0/{{ file_version }}"
nagios_core_tarball: "/home/vagrant/nagios-4.1.0rc1.tar.gz"
