---

  - name: download nagios core
    get_url: url="{{nagios_core_url}}" dest="{{home_directory}}/"

  - name: extract nagios tarball
    unarchive: src={{home_directory}}/{{file_version}}.tar.gz
               dest={{home_directory}}
               copy=no
    register: unarchive

  - name: configure nagios core for compiliation
    shell: "./configure --prefix=/usr/local/nagios --with-nagios-user=nagios --with-nagios-group=nagios --with-command-user=nagios --with-command-group=nagcmd"
    register: config_result
    when: unarchive|changed
    args:
      chdir: "{{home_directory}}/{{file_version}}/"
