---

  - name: download nagios core
    get_url: url="{{nagios_core_url}}" dest="{{home_directory}}/"

  - name: extract nagios tarball
    unarchive: src={{home_directory}}/{{file_version}}.tar.gz
               dest={{home_directory}}
               copy=no
