---

  - name: download nagios core
    get_url: url="{{nagios_core_url}}" dest="{{nagios_core_tarball}}" force=yes

  - name: extract nagios tarball
    shell: "/bin/tar xf {{ nagios_core_tarball }}"
    register: result
    failed_when: "result.rc != 0"
